# Generated by Django 3.2.7 on 2021-09-06 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=None, max_length=100)),
                ('lname', models.CharField(default=None, max_length=100)),
                ('dob', models.DateField(default=None)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default=1, max_length=15)),
                ('email', models.EmailField(default=None, max_length=256, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('profile_pic', models.ImageField(default=None, upload_to='basic_app/profile_pics')),
                ('number', models.TextField(blank=True, default=None)),
                ('address', models.TextField(default=None, max_length=256)),
                ('city', models.CharField(default=None, max_length=128)),
                ('zip', models.IntegerField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
