# Generated by Django 3.2.7 on 2021-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20210906_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='number',
            field=models.CharField(default=None, max_length=111, null=True),
        ),
    ]
