# Generated by Django 3.2.7 on 2021-09-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_userprofileinfo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-avatar.png', upload_to='basic_app/profile_pics'),
        ),
    ]
